//! Connect RPC surface for the ArcBox sandbox API.
//!
//! The sandbox contract (`arcbox.sandbox.v1`) is the product's public API,
//! so it is served over Connect rather than plain gRPC: one set of handlers
//! answers Connect (HTTP POST with JSON or binary protobuf), gRPC, and
//! gRPC-Web. A caller with no proto toolchain can reach it with `curl`,
//! native clients keep gRPC performance, and browsers get gRPC-Web.
//!
//! Message types here are generated by buffa, not prost. During the
//! message-layer convergence (CORE-73) they are becoming the ONE Rust
//! representation of the `.proto` files for ArcBox-owned protocols:
//!
//! * The **public boundary** (client ↔ daemon) uses these buffa types,
//!   because `connectrpc` is bound to `buffa::Message`.
//! * The **guest agent** encodes its vsock frames with these types too —
//!   the crate compiles for `aarch64-unknown-linux-musl` (base `connectrpc`
//!   is transport-free) and must stay musl-clean.
//! * The **host side of the vsock wire** still uses the prost twins in
//!   `arcbox-protocol` until the remaining CORE-73 phases land.
//!
//! buffa and prost encode identical protobuf bytes, so mixed-codec peers
//! interoperate; both representations are generated from the same `.proto`
//! sources and therefore cannot drift.

connectrpc::include_generated!();

/// The sandbox package, under the same short alias `arcbox-protocol` uses
/// for its prost twin — so a call site reads `arcbox_connect::sandbox_v1`
/// against `arcbox_protocol::sandbox_v1` and the two are told apart by the
/// crate, not by a path shape.
pub use arcbox::sandbox::v1 as sandbox_v1;

/// The daemon's own package, under the same short alias `arcbox-protocol`
/// uses for its prost twin (CORE-68).
pub use arcbox::v1;
