//! Connect RPC surface for the ArcBox sandbox API.
//!
//! The sandbox contract (`arcbox.sandbox.v1`) is the product's public API,
//! so it is served over Connect rather than plain gRPC: one set of handlers
//! answers Connect (HTTP POST with JSON or binary protobuf), gRPC, and
//! gRPC-Web. A caller with no proto toolchain can reach it with `curl`,
//! native clients keep gRPC performance, and browsers get gRPC-Web.
//!
//! Message types here are generated by buffa, not prost. They are a second
//! Rust representation of the same `.proto` files that `arcbox-protocol`
//! generates with prost — deliberately so:
//!
//! * The **public boundary** (client ↔ daemon) uses these buffa types,
//!   because `connectrpc` is bound to `buffa::Message`.
//! * The **internal vsock wire** (daemon ↔ guest agent) keeps the prost
//!   types in `arcbox_protocol::sandbox_v1`.
//!
//! Both encode standard protobuf bytes, so the vsock frames are identical
//! either way and the guest agent is untouched. The two representations are
//! generated from the same `.proto` sources and therefore cannot drift.

connectrpc::include_generated!();

/// The sandbox package, under the same short alias `arcbox-protocol` uses
/// for its prost twin — so a call site reads `arcbox_connect::sandbox_v1`
/// against `arcbox_protocol::sandbox_v1` and the two are told apart by the
/// crate, not by a path shape.
pub use arcbox::sandbox::v1 as sandbox_v1;
