"""Generate each `_sync` tree from its `_async` source.

Mechanical unasync transform: `async def` -> `def`, `await` dropped,
httpx AsyncClient -> Client, the `Async*` public class names lose their
prefix. The sync trees are committed; CI reruns the transform and fails
on drift (`--check`), and the parity test asserts identical public
surfaces.

Usage:
    uv run python scripts/gen_sync.py          # regenerate every _sync tree
    uv run python scripts/gen_sync.py --check  # verify, exit 1 on drift
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import unasync

SDK_ROOT = Path(__file__).resolve().parent.parent
PACKAGE = SDK_ROOT / "src" / "arcbox"

#: Every async tree, by the package-relative prefix its modules sit
#: under. Each gets its own `_sync` sibling; the transform and the
#: replacement table below are shared, because the naming convention is.
TREES = ("", "e2b")

HEADER = "# Generated by scripts/gen_sync.py from arcbox/{origin}/{name} — do not edit.\n"


def async_dir(tree: str) -> Path:
    """Source tree for `tree` (`""` is the SDK's own)."""
    return (PACKAGE / tree / "_async") if tree else (PACKAGE / "_async")


def sync_dir(tree: str) -> Path:
    """Committed sync tree for `tree`."""
    return (PACKAGE / tree / "_sync") if tree else (PACKAGE / "_sync")


def origin(tree: str) -> str:
    """Package-relative path of `tree`'s async dir, for the file header."""
    return f"{tree}/_async" if tree else "_async"


# On top of unasync's defaults (async def/await/async for/async with,
# __aenter__/__aexit__/__aiter__/__anext__, AsyncIterator/AsyncIterable,
# StopAsyncIteration, ...).
EXTRA_REPLACEMENTS = {
    # Public class names lose their Async prefix.
    "AsyncArcBox": "ArcBox",
    "AsyncSandbox": "Sandbox",
    "AsyncCommands": "Commands",
    "AsyncCommandHandle": "CommandHandle",
    "AsyncOutputStream": "OutputStream",
    "AsyncEventStream": "EventStream",
    "AsyncFileWatch": "FileWatch",
    "AsyncFiles": "Files",
    "AsyncPorts": "Ports",
    "AsyncConnectClient": "ConnectClient",
    "AsyncServerStream": "ServerStream",
    # The e2b tree's public class names.
    "AsyncFilesystem": "Filesystem",
    "AsyncPty": "Pty",
    "AsyncGit": "Git",
    "AsyncWatchHandle": "WatchHandle",
    # Watch teardown differs per flavor (see arcbox/e2b/_pump.py).
    "async_stop_watch": "stop_watch",
    # Output-pump flavors (see arcbox/e2b/_pump.py): a task on the event
    # loop and a daemon thread are different machinery, not a token
    # rewrite of one another.
    "AsyncPump": "Pump",
    "async_call": "call",
    # httpx sync flavors.
    "AsyncClient": "Client",
    "AsyncHTTPTransport": "HTTPTransport",
    "aiter_bytes": "iter_bytes",
    "aread": "read",
    "aclose": "close",
    # typing / contextlib counterparts not in unasync's defaults.
    "AbstractAsyncContextManager": "AbstractContextManager",
    "aclosing": "closing",
    "anext": "next",
    # The event-loop sleep becomes a thread sleep (`asyncio.sleep` ->
    # `time.sleep`; the duplicate `import time` is deduplicated by the
    # ruff pass below).
    "asyncio": "time",
}


def generate(tree: str, target_dir: Path) -> None:
    source_dir = async_dir(tree)
    sources = sorted(str(p) for p in source_dir.glob("*.py"))
    rule = unasync.Rule(
        fromdir=str(source_dir) + "/",
        todir=str(target_dir) + "/",
        additional_replacements=EXTRA_REPLACEMENTS,
    )
    target_dir.mkdir(parents=True, exist_ok=True)
    unasync.unasync_files(sources, [rule])
    for generated in target_dir.glob("*.py"):
        content = generated.read_text()
        generated.write_text(HEADER.format(origin=origin(tree), name=generated.name) + content)
    # The token transform can unsort imports (AsyncIterator -> Iterator);
    # the project's own ruff normalizes the result so the committed tree
    # passes the repo gates verbatim. --config pins the project config
    # even when generating into a scratch dir (the --check path).
    config = str(SDK_ROOT / "pyproject.toml")
    # --ignore UP028 mirrors the pyproject per-file-ignore for the sync
    # trees (this invocation lints nothing else): the --check scratch dir
    # sits outside the project root, where those patterns cannot anchor.
    for args in (["check", "--fix", "--quiet", "--ignore", "UP028"], ["format", "--quiet"]):
        subprocess.run(
            ["ruff", *args, "--config", config, "--no-cache", str(target_dir)],
            check=True,
        )


def check() -> list[str]:
    """Regenerate into a scratch dir and diff against the committed trees.

    Returns the offending relative paths (empty = in lockstep).
    """
    drifted: list[str] = []
    for tree in TREES:
        with tempfile.TemporaryDirectory() as tmp:
            fresh_dir = Path(tmp) / "_sync"
            generate(tree, fresh_dir)
            fresh = {p.name: p.read_text() for p in fresh_dir.glob("*.py")}
            committed_dir = sync_dir(tree)
            committed = (
                {p.name: p.read_text() for p in committed_dir.glob("*.py")}
                if committed_dir.is_dir()
                else {}
            )
            prefix = committed_dir.relative_to(SDK_ROOT)
            for name in sorted(fresh.keys() | committed.keys()):
                if fresh.get(name) != committed.get(name):
                    drifted.append(f"{prefix}/{name}")
    return drifted


def main() -> int:
    if "--check" in sys.argv[1:]:
        drifted = check()
        if drifted:
            print("a sync tree is out of lockstep with its _async source; regenerate with")
            print("  uv run python scripts/gen_sync.py")
            for path in drifted:
                print(f"  drifted: {path}")
            return 1
        print("sync tree in lockstep")
        return 0
    for tree in TREES:
        target = sync_dir(tree)
        if target.exists():
            shutil.rmtree(target)
        generate(tree, target)
        print(f"regenerated {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
