"""Generate the sync tree (`arcbox/_sync`) from the async core.

Mechanical unasync transform: `async def` -> `def`, `await` dropped,
httpx AsyncClient -> Client, the `Async*` public class names lose their
prefix. The sync tree is committed; CI reruns the transform and fails on
drift (`--check`), and the parity test asserts identical public
surfaces.

Usage:
    uv run python scripts/gen_sync.py          # regenerate arcbox/_sync
    uv run python scripts/gen_sync.py --check  # verify, exit 1 on drift
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import unasync

SDK_ROOT = Path(__file__).resolve().parent.parent
ASYNC_DIR = SDK_ROOT / "src" / "arcbox" / "_async"
SYNC_DIR = SDK_ROOT / "src" / "arcbox" / "_sync"

HEADER = "# Generated by scripts/gen_sync.py from arcbox/_async/{name} — do not edit.\n"

# On top of unasync's defaults (async def/await/async for/async with,
# __aenter__/__aexit__/__aiter__/__anext__, AsyncIterator/AsyncIterable,
# StopAsyncIteration, ...).
EXTRA_REPLACEMENTS = {
    # Public class names lose their Async prefix.
    "AsyncArcBox": "ArcBox",
    "AsyncSandbox": "Sandbox",
    "AsyncCommands": "Commands",
    "AsyncCommandHandle": "CommandHandle",
    "AsyncOutputStream": "OutputStream",
    "AsyncEventStream": "EventStream",
    "AsyncFiles": "Files",
    "AsyncConnectClient": "ConnectClient",
    "AsyncServerStream": "ServerStream",
    # httpx sync flavors.
    "AsyncClient": "Client",
    "AsyncHTTPTransport": "HTTPTransport",
    "aiter_bytes": "iter_bytes",
    "aread": "read",
    "aclose": "close",
    # typing / contextlib counterparts not in unasync's defaults.
    "AbstractAsyncContextManager": "AbstractContextManager",
    "aclosing": "closing",
    "anext": "next",
    # The event-loop sleep becomes a thread sleep (`asyncio.sleep` ->
    # `time.sleep`; the duplicate `import time` is deduplicated by the
    # ruff pass below).
    "asyncio": "time",
}


def generate(target_dir: Path) -> None:
    sources = sorted(str(p) for p in ASYNC_DIR.glob("*.py"))
    rule = unasync.Rule(
        fromdir=str(ASYNC_DIR) + "/",
        todir=str(target_dir) + "/",
        additional_replacements=EXTRA_REPLACEMENTS,
    )
    target_dir.mkdir(parents=True, exist_ok=True)
    unasync.unasync_files(sources, [rule])
    for generated in target_dir.glob("*.py"):
        content = generated.read_text()
        generated.write_text(HEADER.format(name=generated.name) + content)
    # The token transform can unsort imports (AsyncIterator -> Iterator);
    # the project's own ruff normalizes the result so the committed tree
    # passes the repo gates verbatim. --config pins the project config
    # even when generating into a scratch dir (the --check path).
    config = str(SDK_ROOT / "pyproject.toml")
    # --ignore UP028 mirrors the pyproject per-file-ignore for the sync
    # tree (this invocation lints nothing else): the --check scratch dir
    # sits outside the project root, where that pattern cannot anchor.
    for args in (["check", "--fix", "--quiet", "--ignore", "UP028"], ["format", "--quiet"]):
        subprocess.run(
            ["ruff", *args, "--config", config, "--no-cache", str(target_dir)],
            check=True,
        )


def check() -> list[str]:
    """Regenerate into a scratch dir and diff against the committed tree.

    Returns the offending relative paths (empty = in lockstep).
    """
    drifted: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        fresh_dir = Path(tmp) / "_sync"
        generate(fresh_dir)
        fresh = {p.name: p.read_text() for p in fresh_dir.glob("*.py")}
        committed = (
            {p.name: p.read_text() for p in SYNC_DIR.glob("*.py")} if SYNC_DIR.is_dir() else {}
        )
        for name in sorted(fresh.keys() | committed.keys()):
            if fresh.get(name) != committed.get(name):
                drifted.append(f"src/arcbox/_sync/{name}")
    return drifted


def main() -> int:
    if "--check" in sys.argv[1:]:
        drifted = check()
        if drifted:
            print("sync tree out of lockstep with arcbox/_async; regenerate with")
            print("  uv run python scripts/gen_sync.py")
            for path in drifted:
                print(f"  drifted: {path}")
            return 1
        print("sync tree in lockstep")
        return 0
    if SYNC_DIR.exists():
        shutil.rmtree(SYNC_DIR)
    generate(SYNC_DIR)
    print(f"regenerated {SYNC_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
