# Generated by scripts/gen_sync.py from arcbox/_async/commands.py — do not edit.
"""The ``sandbox.commands`` namespace: run processes inside one sandbox."""

from __future__ import annotations

import math
import time
import uuid
from contextlib import closing, suppress
from typing import TYPE_CHECKING, Literal, overload

import httpx
from google.protobuf import empty_pb2

from arcbox._boundary import wrap_errors
from arcbox._gen import process_pb2
from arcbox._types import (
    SIGNAL_VALUES,
    CommandResult,
    OutputChunk,
    StdinStatus,
    command_info_from_proto,
    command_result_from_execution,
)
from arcbox.errors import (
    ArcBoxError,
    ConnectionFailedError,
    ConnectionLostError,
    InvalidArgumentError,
    TimeoutError,
)

if TYPE_CHECKING:
    import re
    from collections.abc import Generator, Iterator, Mapping, Sequence
    from types import TracebackType

    from arcbox._types import CommandInfo, OutputChannel, PtySize, SignalName

    from ._client import ConnectClient, ServerStream

_PROCESS = "/arcbox.sandbox.v1.SandboxProcessService/"

#: Longest single WaitExecution long-poll slice, so a dropped daemon
#: surfaces as an error instead of an infinite silent wait.
_WAIT_SLICE_SECONDS = 30

#: Consecutive dead re-attach dials tolerated before an output stream
#: surfaces the stream-death error. Delivered output resets the budget,
#: so a long-lived stream survives any number of isolated drops.
_MAX_ATTACH_RETRIES = 3


def _normalize_cmd(cmd: str | Sequence[str]) -> list[str]:
    """``str`` is sugar for a shell command; a sequence is argv, executed
    directly with no shell involved."""
    return ["/bin/sh", "-lc", cmd] if isinstance(cmd, str) else list(cmd)


def _channel_name(channel: int) -> OutputChannel:
    if channel == process_pb2.STDIO_CHANNEL_STDERR:
        return "stderr"
    if channel == process_pb2.STDIO_CHANNEL_PTY:
        return "pty"
    return "stdout"


def _decode_output(chunks: list[bytes]) -> str:
    return b"".join(chunks).decode("utf-8", errors="replace")


class _LogScanner:
    """Line-oriented pattern scanner over per-channel byte streams. Each
    channel keeps its own partial-line buffer, so interleaved chunks
    never corrupt a line and a chunk-split line still matches. Lines are
    decoded only when complete (a ``\\n`` byte is unambiguous in UTF-8,
    so multi-byte sequences never split a line). Memory is bounded by
    the longest line, not the output length."""

    def __init__(self, pattern: str | re.Pattern[str]) -> None:
        self._pattern = pattern
        self._partials: dict[int, bytes] = {}

    def _matches(self, line: str) -> bool:
        if isinstance(self._pattern, str):
            return self._pattern in line
        return self._pattern.search(line) is not None

    def push(self, channel: int, data: bytes) -> str | None:
        """Feed one chunk; returns the first matching complete line."""
        lines = (self._partials.get(channel, b"") + data).split(b"\n")
        # The final element is the new unterminated tail.
        self._partials[channel] = lines.pop()
        for raw in lines:
            line = raw.decode("utf-8", errors="replace")
            if self._matches(line):
                return line
        return None

    def flush(self) -> str | None:
        """End of output: test the unterminated tails too."""
        for raw in self._partials.values():
            if raw:
                line = raw.decode("utf-8", errors="replace")
                if self._matches(line):
                    return line
        return None


def _wait_for_log_timeout(command_id: str, pattern: str | re.Pattern[str]) -> TimeoutError:
    return TimeoutError(
        "wait_for_log(timeout) elapsed before the log pattern appeared",
        suggestion="increase the wait_for_log timeout argument",
        context={"command_id": command_id, "pattern": str(pattern)},
    )


class OutputStream:
    """A command's output, iterable chunk by chunk.

    Consuming it to the end releases the underlying HTTP stream
    deterministically. When exiting early (``break``), iterate inside
    the context-manager form — ``async with handle.output as stream`` in
    the async flavor, ``with`` in the sync one — so the stream closes at
    the break instead of whenever the generator finalizer runs."""

    def __init__(self, chunks: Generator[OutputChunk]) -> None:
        self._chunks = chunks

    def __iter__(self) -> Iterator[OutputChunk]:
        return self._chunks

    def close(self) -> None:
        """Release the underlying HTTP stream without consuming the rest."""
        self._chunks.close()

    def __enter__(self) -> OutputStream:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()


class CommandHandle:
    """A handle to a running (or finished) command. The process is
    decoupled from this object: dropping the handle never kills the
    process."""

    def __init__(
        self,
        client: ConnectClient,
        sandbox_id: str,
        command_id: str,
        *,
        stdin_offset: int | None = 0,
    ) -> None:
        self._client = client
        self._sandbox_id = sandbox_id
        #: Execution id, unique within the sandbox; addressable across clients.
        self.command_id = command_id
        # The next stdin write offset — advanced only on a successful
        # write, so a retried write lands at the same offset and the
        # daemon's deduplication makes it idempotent. None = unknown (a
        # re-attached handle); resynced lazily via GetStdinStatus.
        self._stdin_offset = stdin_offset

    @property
    def output(self) -> OutputStream:
        """Stream the command's output from the beginning — or from the
        earliest byte the daemon still retains (8 MiB per channel);
        replayed buffered output comes first, then live output follows;
        the stream ends when the process exits (deterministic
        termination — never silence). A transport drop mid-stream
        re-attaches transparently from the last delivered offsets (see
        :class:`arcbox.errors.ConnectionLostError` for the
        exhausted-retries case). When breaking out early, iterate via
        the context-manager form (see :class:`AsyncOutputStream`)."""
        return OutputStream(self._stream_output())

    def _stream_output(self) -> Generator[OutputChunk]:
        # aclosing releases the inner attach loop (and its HTTP stream)
        # deterministically on early exit — breaking out of an async-for
        # alone would leave it to generator finalization.
        with closing(self._attach_events("commands.output")) as events:
            for event in events:
                kind = event.WhichOneof("event")
                if kind == "output":
                    chunk = event.output
                    yield OutputChunk(_channel_name(chunk.channel), chunk.data)
                elif kind == "exited":
                    return

    def _attach_events(self, operation: str) -> Generator[process_pb2.ExecutionEvent]:
        """The resumable attach loop shared by :attr:`output` and the
        result collection: streams execution events, tracking the byte
        offset each channel has delivered. When the transport drops
        mid-stream, it re-attaches from those offsets — the daemon
        replays nothing already delivered — so the consumer sees one
        seamless, gapless stream. Only consecutive dead dials count
        against the retry budget (delivered output resets it); once
        exhausted, the stream-death
        :class:`arcbox.errors.ConnectionLostError` carries the last
        transport failure. Daemon-typed stream errors are never
        retried."""
        with wrap_errors(operation):
            stdout_offset = 0
            stderr_offset = 0
            failures = 0
            while True:
                try:
                    with self._attach(stdout_offset, stderr_offset) as stream:
                        for event in stream:
                            kind = event.WhichOneof("event")
                            if kind == "output":
                                chunk = event.output
                                after = chunk.offset + len(chunk.data)
                                if chunk.channel == process_pb2.STDIO_CHANNEL_STDERR:
                                    if after > stderr_offset:
                                        stderr_offset = after
                                        failures = 0
                                elif after > stdout_offset:
                                    stdout_offset = after
                                    failures = 0
                            yield event
                            if kind == "exited":
                                return
                    # A clean server-side end without an exited frame:
                    # nothing more is coming (the daemon closed the record).
                    return
                # ConnectionFailedError covers the drop's OTHER wire shape:
                # the daemon losing its upstream agent stream ends the HTTP
                # stream cleanly with a Connect `unavailable` error frame,
                # decoded into ConnectionFailedError (ConnectionLostError —
                # raw truncation — is its subclass). Daemon-typed errors
                # map to other classes and are never retried.
                except (httpx.HTTPError, ConnectionFailedError) as exc:
                    failures += 1
                    if failures > _MAX_ATTACH_RETRIES:
                        raise ConnectionLostError(
                            "the output stream died and could not be re-attached "
                            "within the retry budget",
                            context={
                                "command_id": self.command_id,
                                "retries": str(_MAX_ATTACH_RETRIES),
                            },
                            operation=operation,
                        ) from exc

    def wait_for_exit(self, timeout: float | None = None) -> CommandResult:
        """Wait until the command exits and return its result (server-side
        long-poll; no client-side spinning). ``timeout`` bounds the WAIT,
        not the process: on expiry a :class:`TimeoutError` is raised and
        the process keeps running."""
        deadline = None if timeout is None else time.monotonic() + timeout
        with wrap_errors("commands.wait_for_exit"):
            while True:
                remaining = None if deadline is None else deadline - time.monotonic()
                if remaining is not None and remaining <= 0:
                    raise TimeoutError(
                        "wait_for_exit(timeout) elapsed before the command exited",
                        suggestion=(
                            "increase the wait_for_exit timeout argument, or kill() the command"
                        ),
                        context={"command_id": self.command_id},
                    )
                if remaining is None:
                    execution = self._wait_slice(_WAIT_SLICE_SECONDS)
                elif remaining >= 1:
                    execution = self._wait_slice(min(_WAIT_SLICE_SECONDS, int(remaining)))
                else:
                    # The wire's wait granularity is whole seconds. Poll
                    # immediately (an already-exited command returns at
                    # once); only if it is still running, sleep out the
                    # remainder and take one final poll so an exit inside
                    # the budget is still caught — past it, the deadline
                    # check above raises.
                    execution = self._wait_slice(0)
                    if execution.state != process_pb2.EXECUTION_STATE_EXITED:
                        time.sleep(remaining)
                        execution = self._wait_slice(0)
                if execution.state == process_pb2.EXECUTION_STATE_EXITED:
                    break
            return self._collect_result(execution)

    def wait_for_log(self, pattern: str | re.Pattern[str], timeout: float | None = None) -> str:
        """Wait until a log line matching ``pattern`` appears on any of
        the command's output channels, and return that line. A ``str``
        pattern is substring containment; a compiled
        :class:`re.Pattern` is searched per line. Purely SDK-side — no
        daemon RPC beyond the attach: the offset-addressed output
        replays from the beginning (or the earliest retained byte), so
        a line printed before the call matches immediately, and a
        transport drop resumes through the same re-attach loop as
        :attr:`output`.

        Matching is line-oriented: complete lines are tested as they
        arrive, and a trailing unterminated line is tested once the
        command exits. If the command exits (or the daemon closes the
        record) before any match, an :class:`ArcBoxError` is raised —
        that is not a timeout. ``timeout`` bounds the WAIT, not the
        process; expiry raises :class:`TimeoutError` naming this knob.
        The deadline is observed on stream frames (the daemon
        interleaves keepalives while idle), so expiry can lag by up to
        the keepalive interval."""
        deadline = None if timeout is None else time.monotonic() + timeout
        scanner = _LogScanner(pattern)
        with wrap_errors("commands.wait_for_log"):
            try:
                with closing(self._attach_events("commands.wait_for_log")) as events:
                    for event in events:
                        # Deadline first, so a frame landing past expiry
                        # cannot flip a timeout into a late success (or
                        # a late exit error) — the strictness the TS
                        # flavor gets from aborting the attach stream.
                        if deadline is not None and time.monotonic() >= deadline:
                            raise _wait_for_log_timeout(self.command_id, pattern)
                        kind = event.WhichOneof("event")
                        if kind == "output":
                            line = scanner.push(event.output.channel, event.output.data)
                            if line is not None:
                                return line
                        elif kind == "exited":
                            break
            except ConnectionLostError as exc:
                # The re-attach budget dying past the deadline is the
                # deadline surfacing, mirroring connect()'s discipline.
                if deadline is not None and time.monotonic() >= deadline:
                    raise _wait_for_log_timeout(self.command_id, pattern) from exc
                raise
            if deadline is not None and time.monotonic() >= deadline:
                raise _wait_for_log_timeout(self.command_id, pattern)
            # The command exited (or the daemon closed the record): a
            # trailing unterminated line still counts.
            tail = scanner.flush()
            if tail is not None:
                return tail
            raise ArcBoxError(
                "the command exited before the log pattern appeared",
                context={"command_id": self.command_id, "pattern": str(pattern)},
            )

    def _wait_slice(self, slice_seconds: int) -> process_pb2.Execution:
        """One WaitExecution long-poll (0 = an immediate state poll)."""
        return self._client.unary(
            _PROCESS + "WaitExecution",
            process_pb2.WaitExecutionRequest(
                sandbox_id=self._sandbox_id,
                execution_id=self.command_id,
                timeout_seconds=slice_seconds,
            ),
            process_pb2.Execution,
            # Exempt from request_timeout: this unary deliberately parks
            # server-side for the slice; grant it that long plus grace.
            timeout=float(slice_seconds + 5),
        )

    def kill(self, signal: SignalName = "SIGTERM") -> None:
        """Deliver a signal to the whole process group (default SIGTERM)."""
        with wrap_errors("commands.kill"):
            self._client.unary(
                _PROCESS + "SignalExecution",
                process_pb2.SignalExecutionRequest(
                    sandbox_id=self._sandbox_id,
                    execution_id=self.command_id,
                    signal=SIGNAL_VALUES[signal],
                ),
                empty_pb2.Empty,
            )

    def write_stdin(self, data: str | bytes) -> None:
        """Write bytes (or a UTF-8 string) to the command's stdin.
        Requires a run started with ``stdin=True`` or a PTY.

        Writes are offset-idempotent: the handle tracks the stdin cursor
        and advances it only on success, so retrying a failed or lost
        write *with the same data* is safe — the daemon deduplicates
        bytes below its accepted count and never double-feeds the
        process. Issue writes sequentially; the handle tracks a single
        cursor."""
        payload = data.encode() if isinstance(data, str) else data
        with wrap_errors("commands.write_stdin"):
            offset = self._stdin_cursor()
            status = self._client.unary(
                _PROCESS + "WriteStdin",
                process_pb2.WriteStdinRequest(
                    sandbox_id=self._sandbox_id,
                    execution_id=self.command_id,
                    offset=offset,
                    data=payload,
                    eof=False,
                ),
                process_pb2.StdinStatus,
            )
            self._stdin_offset = int(status.bytes_written)

    def close_stdin(self) -> None:
        """Close the command's stdin (EOF). Rejected for PTY commands —
        write Ctrl-D (``"\\x04"``) instead."""
        with wrap_errors("commands.close_stdin"):
            offset = self._stdin_cursor()
            self._client.unary(
                _PROCESS + "WriteStdin",
                process_pb2.WriteStdinRequest(
                    sandbox_id=self._sandbox_id,
                    execution_id=self.command_id,
                    offset=offset,
                    data=b"",
                    eof=True,
                ),
                process_pb2.StdinStatus,
            )

    def stdin_status(self) -> StdinStatus:
        """The daemon's stdin acceptance state — the recovery point after
        a lost write response. Also resyncs the handle's write cursor."""
        with wrap_errors("commands.stdin_status"):
            status = self._fetch_stdin_status()
            return StdinStatus(bytes_written=int(status.bytes_written), closed=status.closed)

    def resize(self, cols: int, rows: int) -> None:
        """Resize a PTY command's terminal."""
        with wrap_errors("commands.resize"):
            self._client.unary(
                _PROCESS + "ResizeExecutionTty",
                process_pb2.ResizeExecutionTtyRequest(
                    sandbox_id=self._sandbox_id,
                    execution_id=self.command_id,
                    size=process_pb2.TerminalSize(width=cols, height=rows),
                ),
                empty_pb2.Empty,
            )

    def _stdin_cursor(self) -> int:
        """The tracked stdin cursor, resynced from the daemon when unknown."""
        offset = self._stdin_offset
        if offset is None:
            offset = int((self._fetch_stdin_status()).bytes_written)
        return offset

    def _fetch_stdin_status(self) -> process_pb2.StdinStatus:
        status = self._client.unary(
            _PROCESS + "GetStdinStatus",
            process_pb2.GetStdinStatusRequest(
                sandbox_id=self._sandbox_id, execution_id=self.command_id
            ),
            process_pb2.StdinStatus,
        )
        self._stdin_offset = int(status.bytes_written)
        return status

    def _attach(
        self, stdout_offset: int, stderr_offset: int
    ) -> ServerStream[process_pb2.ExecutionEvent]:
        return self._client.stream(
            _PROCESS + "AttachExecution",
            process_pb2.AttachExecutionRequest(
                sandbox_id=self._sandbox_id,
                execution_id=self.command_id,
                stdout_offset=stdout_offset,
                stderr_offset=stderr_offset,
            ),
            process_pb2.ExecutionEvent,
        )

    def _collect_result(self, execution: process_pb2.Execution) -> CommandResult:
        """Assemble the result of an exited execution. Output is re-read
        from offset 0 — the daemon retains and replays it, so the result
        is complete even when nobody consumed the live stream, UNLESS the
        command outgrew the daemon's per-channel retention (8 MiB): chunk
        offsets expose the dropped head, reported as ``truncated``."""
        stdout: list[bytes] = []
        stderr: list[bytes] = []
        next_stdout = 0
        next_stderr = 0
        truncated = False
        with closing(self._attach_events("commands.wait_for_exit")) as events:
            for event in events:
                kind = event.WhichOneof("event")
                if kind == "output":
                    chunk = event.output
                    is_stderr = chunk.channel == process_pb2.STDIO_CHANNEL_STDERR
                    # A chunk landing past the expected offset means
                    # retention already dropped bytes we asked for.
                    if chunk.offset > (next_stderr if is_stderr else next_stdout):
                        truncated = True
                    after = chunk.offset + len(chunk.data)
                    if is_stderr:
                        next_stderr = after
                        stderr.append(chunk.data)
                    else:
                        next_stdout = after
                        stdout.append(chunk.data)
                elif kind == "exited":
                    break
        return command_result_from_execution(
            execution, _decode_output(stdout), _decode_output(stderr), truncated
        )


class Commands:
    """Run processes inside one sandbox."""

    def __init__(self, client: ConnectClient, sandbox_id: str) -> None:
        self._client = client
        self._sandbox_id = sandbox_id

    @overload
    def run(
        self,
        cmd: str | Sequence[str],
        *,
        cwd: str | None = None,
        env: Mapping[str, str] | None = None,
        user: str | None = None,
        timeout: float | None = None,
        check: bool = False,
        background: Literal[False] = False,
        pty: PtySize | None = None,
        stdin: str | bytes | bool | None = None,
    ) -> CommandResult: ...

    @overload
    def run(
        self,
        cmd: str | Sequence[str],
        *,
        cwd: str | None = None,
        env: Mapping[str, str] | None = None,
        user: str | None = None,
        timeout: float | None = None,
        background: Literal[True],
        pty: PtySize | None = None,
        stdin: str | bytes | bool | None = None,
    ) -> CommandHandle: ...

    def run(
        self,
        cmd: str | Sequence[str],
        *,
        cwd: str | None = None,
        env: Mapping[str, str] | None = None,
        user: str | None = None,
        timeout: float | None = None,
        check: bool = False,
        background: bool = False,
        pty: PtySize | None = None,
        stdin: str | bytes | bool | None = None,
    ) -> CommandResult | CommandHandle:
        """Run a command. Foreground (default): returns the complete
        :class:`CommandResult` once the process exits — non-zero exit is
        data unless ``check=True`` (`subprocess.run` semantics).
        Background (``background=True``): returns as soon as the process
        is started, with a handle for streaming and waiting.

        ``timeout`` kills the whole process group after that many
        seconds; expiry surfaces as signal death in the result
        (exit-as-data), not as a raised error.

        ``pty`` allocates a pseudo-terminal of that size: output then
        arrives merged on the ``"pty"`` channel and stdin stays open —
        end input by writing Ctrl-D (``"\\x04"``) via ``write_stdin``.

        ``stdin``: a string (UTF-8) or bytes is written and then closed
        before the run resolves (subprocess semantics); ``True`` keeps
        stdin open for manual ``write_stdin``/``close_stdin`` —
        background runs only. ``None``/``False``: the process starts
        with stdin already at EOF."""
        if background and check:
            raise InvalidArgumentError(
                "check=True applies to foreground runs; call "
                ".wait_for_exit() and .expect() on the handle instead",
                operation="commands.run",
            )
        if stdin is True and not background:
            raise InvalidArgumentError(
                "stdin=True keeps stdin open for the handle and requires "
                "background=True; pass str or bytes to feed a foreground run",
                operation="commands.run",
            )
        stdin_data = stdin.encode() if isinstance(stdin, str) else stdin
        if isinstance(stdin_data, bytes) and pty is not None:
            raise InvalidArgumentError(
                "a PTY's stdin cannot be closed after a one-shot write; use "
                'background=True with write_stdin, ending input with Ctrl-D ("\\x04")',
                operation="commands.run",
            )
        handle = self._start(
            cmd,
            cwd=cwd,
            env=env,
            user=user,
            timeout=timeout,
            pty=pty,
            stdin_open=stdin is True or isinstance(stdin_data, bytes),
        )
        if isinstance(stdin_data, bytes):
            self._feed_stdin(handle, stdin_data)
        if background:
            return handle
        result = handle.wait_for_exit()
        return result.expect() if check else result

    def get(self, command_id: str) -> CommandHandle:
        """Re-attach to an execution by id — from another process, or
        after losing the handle. Verifies the execution exists (an
        unknown id is a typed not-found error) and seeds the handle's
        stdin cursor from the daemon's accepted count so later writes
        resume without a gap."""
        with wrap_errors("commands.get"):
            execution = self._client.unary(
                _PROCESS + "WaitExecution",
                process_pb2.WaitExecutionRequest(
                    sandbox_id=self._sandbox_id,
                    execution_id=command_id,
                    timeout_seconds=0,
                ),
                process_pb2.Execution,
            )
            stdin_offset = (
                int(execution.stdin.bytes_written) if execution.HasField("stdin") else None
            )
            return CommandHandle(
                self._client, self._sandbox_id, execution.id, stdin_offset=stdin_offset
            )

    def list(self) -> list[CommandInfo]:
        """List this sandbox's commands, running and exited — the
        rediscovery path after losing handles (or a whole process):
        pick an id from a summary and :meth:`get` a live handle for it.
        Running executions stay listed as long as they run; exited ones
        are retained for a bounded window after exit (currently five
        minutes guest-side) and then dropped, after which neither
        ``list`` nor ``get`` rediscovers them."""
        with wrap_errors("commands.list"):
            listing = self._client.unary(
                _PROCESS + "ListExecutions",
                process_pb2.ListExecutionsRequest(sandbox_id=self._sandbox_id),
                process_pb2.ListExecutionsResponse,
            )
            return [command_info_from_proto(execution) for execution in listing.executions]

    def _start(
        self,
        cmd: str | Sequence[str],
        *,
        cwd: str | None,
        env: Mapping[str, str] | None,
        user: str | None,
        timeout: float | None,
        pty: PtySize | None,
        stdin_open: bool,
    ) -> CommandHandle:
        with wrap_errors("commands.run"):
            # The execution id is minted client-side: a lost response
            # leaves an addressable execution, and retries are idempotent
            # by contract.
            execution_id = str(uuid.uuid4())
            request = process_pb2.StartExecutionRequest(
                sandbox_id=self._sandbox_id,
                execution_id=execution_id,
                cmd=_normalize_cmd(cmd),
                env=dict(env) if env else {},
                working_dir=cwd or "",
                user=user or "",
                timeout_seconds=0 if timeout is None else math.ceil(timeout),
                # A PTY inherently keeps stdin open (EOF is not
                # expressible on a terminal); otherwise stdin stays open
                # exactly when the caller feeds or drives it.
                stdin=pty is not None or stdin_open,
                tty=pty is not None,
            )
            if pty is not None:
                request.tty_size.width = pty.cols
                request.tty_size.height = pty.rows
            execution = self._client.unary(
                _PROCESS + "StartExecution", request, process_pb2.Execution
            )
            return CommandHandle(self._client, self._sandbox_id, execution.id)

    def _feed_stdin(self, handle: CommandHandle, data: bytes) -> None:
        """Write-then-close the one-shot stdin payload. A process is free
        to exit without consuming its stdin (`subprocess` semantics):
        when the feed fails but the execution has already exited, the
        exit result is the truth and the failed feed is noise — the
        write merely raced the exit. Any other failure is real and
        surfaces."""
        try:
            handle.write_stdin(data)
            handle.close_stdin()
        except ArcBoxError:
            state: process_pb2.Execution | None = None
            # If the poll itself fails, the original feed error stands.
            with suppress(Exception):
                state = self._client.unary(
                    _PROCESS + "WaitExecution",
                    process_pb2.WaitExecutionRequest(
                        sandbox_id=self._sandbox_id,
                        execution_id=handle.command_id,
                        timeout_seconds=0,
                    ),
                    process_pb2.Execution,
                )
            if state is None or state.state != process_pb2.EXECUTION_STATE_EXITED:
                # The caller gets no handle out of a thrown run(), so a
                # still-running process (cat waiting on input) would
                # keep the sandbox RUNNING with no way to reach it.
                # Best-effort kill; the feed error is the one to surface.
                with suppress(Exception):
                    handle.kill("SIGKILL")
                raise
