# Generated by scripts/gen_sync.py from arcbox/_async/templates.py — do not edit.
"""Template catalog client (CORE-107): build, publish, resolve, list,
delete — the named, versioned sandbox bases ``Sandbox.create`` accepts."""

from __future__ import annotations

from typing import TYPE_CHECKING

from google.protobuf import empty_pb2

from arcbox._boundary import wrap_errors
from arcbox._gen import template_pb2
from arcbox._types import TemplateInfo, template_info_from_proto

from ._client import ConnectClient

if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping, Sequence
    from types import TracebackType

    from arcbox._connection import Connection

_TEMPLATE = "/arcbox.sandbox.v1.TemplateService/"


class Template:
    """A catalog template: a named, versioned, reproducible sandbox base.

    ``Sandbox.create`` accepts an instance directly; the reference it pins
    is ``name:version`` for published versions and the bare name for
    drafts."""

    def __init__(self, client: ConnectClient, info: TemplateInfo) -> None:
        self._client = client
        # Flipped by the classmethods that mint their own client: the
        # handle then closes it on explicit close/context exit. Handles
        # sharing a caller-held client (direct construction, ``publish``)
        # never close it.
        self._owns_client = False
        #: Full catalog row.
        self.info = info
        #: Template name, unique in the catalog.
        self.name = info.name
        #: Published version ("" = unpublished draft).
        self.version = info.version
        #: Content digest pinning this version's artifacts.
        self.digest = info.digest

    @property
    def reference(self) -> str:
        """The ``name[:version]`` reference this instance addresses."""
        return self.name if self.version == "" else f"{self.name}:{self.version}"

    @classmethod
    def build(
        cls,
        name: str,
        *,
        image: str | None = None,
        dockerfile: str | None = None,
        snapshot: str | None = None,
        vcpus: int | None = None,
        memory_mib: int | None = None,
        cmd: Sequence[str] | None = None,
        env: Mapping[str, str] | None = None,
        exposed_ports: Sequence[int] | None = None,
        ready_probe_port: int | None = None,
        ready_probe_command: Sequence[str] | None = None,
        ready_probe_timeout: float | None = None,
        labels: Mapping[str, str] | None = None,
        prewarm: bool = False,
        connection: Connection | None = None,
    ) -> Template:
        """Build a template from exactly one source (``image`` — a local
        Docker reference; ``dockerfile`` — inline content, the build
        context is the file alone; ``snapshot`` — promote a checkpoint
        into the warm start point, ``prewarm`` ignored) and register it as
        the catalog draft. Blocks for the whole pipeline — no client
        deadline is applied."""
        sources = [s for s in (image, dockerfile, snapshot) if s is not None]
        if len(sources) != 1:
            msg = "exactly one of image=, dockerfile=, or snapshot= is required"
            raise ValueError(msg)
        request = template_pb2.BuildTemplateRequest(
            name=name,
            labels=dict(labels) if labels else {},
            prewarm=prewarm,
        )
        if image is not None:
            request.docker_ref = image
        elif dockerfile is not None:
            request.dockerfile = dockerfile
        else:
            request.snapshot_id = snapshot or ""
        defaults = request.defaults
        if vcpus is not None or memory_mib is not None:
            defaults.limits.vcpus = vcpus or 0
            defaults.limits.memory_mib = memory_mib or 0
        if cmd:
            defaults.cmd.extend(cmd)
        if env:
            defaults.env.update(env)
        if exposed_ports:
            defaults.exposed_ports.extend(exposed_ports)
        if ready_probe_port is not None and ready_probe_command is not None:
            msg = "ready_probe_port and ready_probe_command are mutually exclusive"
            raise ValueError(msg)
        if ready_probe_port is not None:
            defaults.ready_probe.port = ready_probe_port
        elif ready_probe_command is not None:
            defaults.ready_probe.command.cmd.extend(ready_probe_command)
        if ready_probe_timeout is not None:
            defaults.ready_probe.timeout_seconds = int(ready_probe_timeout)
        client = ConnectClient(connection)
        try:
            with wrap_errors("templates.build"):
                proto = client.unary(
                    _TEMPLATE + "Build",
                    request,
                    template_pb2.Template,
                    timeout=None,
                )
        except BaseException:
            client.close()
            raise
        template = cls(client, template_info_from_proto(proto))
        template._owns_client = True
        return template

    @classmethod
    def get(
        cls,
        reference: str,
        *,
        connection: Connection | None = None,
    ) -> Template:
        """Resolve ``name[:version]`` (bare name = newest published, else
        the draft)."""
        client = ConnectClient(connection)
        try:
            with wrap_errors("templates.get"):
                proto = client.unary(
                    _TEMPLATE + "Get",
                    template_pb2.GetTemplateRequest(reference=reference),
                    template_pb2.Template,
                )
        except BaseException:
            client.close()
            raise
        template = cls(client, template_info_from_proto(proto))
        template._owns_client = True
        return template

    @classmethod
    def list(
        cls,
        *,
        labels: Mapping[str, str] | None = None,
        connection: Connection | None = None,
    ) -> Iterator[TemplateInfo]:
        """List catalog rows — one per version, drafts included
        (auto-paginating). The hidden client closes when iteration
        completes or the iterator is closed; abandoning it mid-iteration
        defers that to generator finalization, so callers that may stop
        early should close the iterator explicitly (e.g.
        ``contextlib.aclosing`` in the async flavor)."""
        client = ConnectClient(connection)
        try:
            with wrap_errors("templates.list"):
                page_token = ""
                while True:
                    page = client.unary(
                        _TEMPLATE + "List",
                        template_pb2.ListTemplatesRequest(
                            labels=dict(labels) if labels else {},
                            page_token=page_token,
                        ),
                        template_pb2.ListTemplatesResponse,
                    )
                    for row in page.templates:
                        yield template_info_from_proto(row)
                    if not page.next_page_token:
                        return
                    page_token = page.next_page_token
        finally:
            client.close()

    @classmethod
    def delete_reference(
        cls,
        reference: str,
        *,
        connection: Connection | None = None,
    ) -> None:
        """Delete ``name`` (the template with every version and its
        artifacts) or ``name:version`` (one version). Sandboxes already
        created from it are unaffected."""
        client = ConnectClient(connection)
        try:
            with wrap_errors("templates.delete"):
                client.unary(
                    _TEMPLATE + "Delete",
                    template_pb2.DeleteTemplateRequest(reference=reference),
                    empty_pb2.Empty,
                )
        finally:
            client.close()

    def close(self) -> None:
        """Release the SDK-owned HTTP client behind a handle minted by
        :meth:`build` or :meth:`get` (no-op for a shared or injected
        client). Also usable as a context manager."""
        if self._owns_client:
            self._client.close()

    def __enter__(self) -> Template:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()

    def publish(self, version: str) -> Template:
        """Freeze the current draft as immutable ``version``.

        The returned handle shares this instance's client and never
        closes it — ownership stays here, exactly as sandbox handles
        share their entry point's client. Keep this handle open while
        using the returned one, or address the published version
        independently via :meth:`get`."""
        with wrap_errors("templates.publish"):
            proto = self._client.unary(
                _TEMPLATE + "Publish",
                template_pb2.PublishTemplateRequest(name=self.name, version=version),
                template_pb2.Template,
            )
        return type(self)(self._client, template_info_from_proto(proto))

    def delete(self) -> None:
        """Delete this exact version (the whole template for a draft)."""
        with wrap_errors("templates.delete"):
            self._client.unary(
                _TEMPLATE + "Delete",
                template_pb2.DeleteTemplateRequest(reference=self.reference),
                empty_pb2.Empty,
            )
