# Generated by scripts/gen_sync.py from arcbox/e2b/_async/filesystem.py — do not edit.
"""The ``sandbox.files`` namespace in ``e2b``'s shape."""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal

from arcbox.e2b._pump import Pump, call, stop_watch
from arcbox.e2b._types import FileType, WriteInfo, to_entry_info, to_filesystem_event
from arcbox.errors import FileNotFoundError

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

    from arcbox import Files, FileWatch
    from arcbox.e2b._types import EntryInfo, FilesystemEvent


class WatchHandle:
    """A running directory watch, from :meth:`AsyncFilesystem.watch_dir`.

    :meth:`stop` cancels it; the sandbox stopping ends it cleanly on
    its own."""

    def __init__(self, watch: FileWatch, pump: Pump, stopped: list[bool]) -> None:
        self._watch = watch
        self._pump = pump
        # Shared with the pump (a one-cell list, set before teardown): a
        # stream error after stop() is the clean end that was asked for,
        # not a watch failure.
        self._stopped = stopped

    def stop(self) -> None:
        """Cancel the watch. Idempotent."""
        self._stopped[0] = True
        stop_watch(self._pump, self._watch)


class Filesystem:
    """``e2b``'s ``Filesystem``, backed by arcbox's ``files``.

    The ``user`` argument is accepted and ignored: the daemon's file
    channel acts as the sandbox's own root, and silently succeeding
    under the wrong identity is better than failing on an argument most
    callers pass out of habit."""

    def __init__(self, files: Files) -> None:
        self._files = files

    def read(
        self,
        path: str,
        format: Literal["text", "bytes"] = "text",
        user: str | None = None,
    ) -> str | bytes:
        """Read a file. ``format='bytes'`` yields ``bytes``, else UTF-8 text."""
        del user
        if format == "bytes":
            return self._files.read_bytes(path)
        return self._files.read_text(path)

    def write(self, path: str, data: str | bytes, user: str | None = None) -> WriteInfo:
        """Write one file."""
        del user
        if isinstance(data, str):
            self._files.write_text(path, data)
        else:
            self._files.write_bytes(path, data)
        return _write_info(path)

    def write_files(self, entries: Sequence[tuple[str, str | bytes]]) -> list[WriteInfo]:
        """Write several files. Sequential — the wire has no batch write."""
        written: list[WriteInfo] = []
        for path, data in entries:
            written.append(self.write(path, data))
        return written

    def list(self, path: str) -> list[EntryInfo]:
        """List a directory's entries, non-recursively."""
        return [to_entry_info(entry, path) for entry in self._files.list(path)]

    def get_info(self, path: str) -> EntryInfo:
        """Metadata of one path."""
        return to_entry_info(self._files.stat(path), _parent_of(path))

    def exists(self, path: str) -> bool:
        """Whether the path exists."""
        try:
            self._files.stat(path)
        except FileNotFoundError:
            return False
        return True

    def make_dir(self, path: str) -> bool:
        """Create a directory and any missing parents.

        Returns ``False`` when it already existed, matching ``e2b``."""
        existed = self.exists(path)
        self._files.mkdir(path)
        return not existed

    def rename(self, old_path: str, new_path: str) -> EntryInfo:
        """Rename or move an entry."""
        self._files.move(old_path, new_path)
        return self.get_info(new_path)

    def remove(self, path: str) -> None:
        """Remove a file, symlink, or directory (recursively)."""
        # e2b's remove takes no recursive flag and deletes directories,
        # so the shim always asks for the recursive form.
        self._files.remove(path, recursive=True)

    def watch_dir(
        self,
        path: str,
        on_event: Callable[[FilesystemEvent], object],
        *,
        recursive: bool = False,
        on_exit: Callable[[BaseException | None], object] | None = None,
    ) -> WatchHandle:
        """Watch a directory and push each change into ``on_event`` —
        ``e2b``'s callback shape over arcbox's event iterable. Event
        paths are made relative to ``path``, matching ``e2b``'s ``name``
        field. ``on_exit`` fires once when the watch ends on its own
        (sandbox stop, or the error that killed it) — not on
        :meth:`AsyncWatchHandle.stop`."""
        watch = self._files.watch(path, recursive=recursive)
        prefix = path if path.endswith("/") else path + "/"
        stopped = [False]

        def pump() -> None:
            error: BaseException | None = None
            try:
                for event in watch:
                    shaped = to_filesystem_event(event, prefix)
                    if shaped is not None:
                        call(on_event, shaped)
            except Exception as exc:
                if stopped[0]:
                    return
                error = exc
            if on_exit is not None:
                call(on_exit, error)

        return WatchHandle(watch, Pump(pump), stopped)


def _write_info(path: str) -> WriteInfo:
    return WriteInfo(name=_basename_of(path), path=path, type=FileType.FILE)


def _basename_of(path: str) -> str:
    return path.rsplit("/", 1)[-1]


def _parent_of(path: str) -> str:
    cut = path.rfind("/")
    return "/" if cut <= 0 else path[:cut]
