# Generated by scripts/gen_sync.py from arcbox/e2b/_async/git.py — do not edit.
"""The ``sandbox.git`` namespace.

``e2b`` implements this as sugar over its command runner — its ``Git``
takes nothing but a ``Commands`` — so this shim does the same, shelling
out to the ``git`` already in the sandbox image. A sandbox without
``git`` surfaces the usual non-zero exit.
"""

from __future__ import annotations

import shlex
from typing import TYPE_CHECKING

from arcbox.e2b.errors import unsupported

if TYPE_CHECKING:
    from collections.abc import Sequence

    from arcbox.e2b._types import CommandResult

    from .commands import Commands


def _git(path: str, args: Sequence[str]) -> str:
    """``git -C <path> …``, the form every verb below uses."""
    return shlex.join(["git", "-C", path, *args])


class Git:
    """Run git operations inside one sandbox."""

    def __init__(self, commands: Commands) -> None:
        self._commands = commands

    def clone(
        self,
        url: str,
        path: str,
        *,
        branch: str | None = None,
        depth: int | None = None,
    ) -> CommandResult:
        """Clone a repository."""
        args = ["git", "clone"]
        if branch is not None:
            args += ["--branch", branch]
        if depth is not None:
            args += ["--depth", str(depth)]
        args += [url, path]
        return self._commands.run(shlex.join(args))

    def init(self, path: str) -> CommandResult:
        """Initialize a repository."""
        return self._commands.run(shlex.join(["git", "init", path]))

    def remote_add(self, path: str, name: str, url: str) -> CommandResult:
        """Add a remote."""
        return self._commands.run(_git(path, ["remote", "add", name, url]))

    def remote_get(self, path: str, name: str) -> CommandResult:
        """Read a remote's URL."""
        return self._commands.run(_git(path, ["remote", "get-url", name]))

    def status(self, path: str) -> CommandResult:
        """Porcelain status of the working tree."""
        return self._commands.run(_git(path, ["status", "--porcelain=v1"]))

    def branches(self, path: str) -> tuple[str | None, list[str]]:
        """List branches, with the current one called out."""
        listing = self._commands.run(_git(path, ["branch", "--format=%(refname:short)"]))
        branches = [line.strip() for line in listing.stdout.splitlines() if line.strip()]
        head = self._commands.run(_git(path, ["rev-parse", "--abbrev-ref", "HEAD"]))
        current = head.stdout.strip()
        return (current or None), branches

    def create_branch(self, path: str, name: str) -> CommandResult:
        """Create a branch."""
        return self._commands.run(_git(path, ["branch", name]))

    def checkout_branch(self, path: str, name: str) -> CommandResult:
        """Check out a branch."""
        return self._commands.run(_git(path, ["checkout", name]))

    def delete_branch(self, path: str, name: str) -> CommandResult:
        """Delete a branch."""
        return self._commands.run(_git(path, ["branch", "-D", name]))

    def add(self, path: str, paths: Sequence[str] | None = None) -> CommandResult:
        """Stage paths (all of them when ``paths`` is empty)."""
        targets = list(paths) if paths else ["."]
        return self._commands.run(_git(path, ["add", *targets]))

    def commit(
        self, path: str, message: str, *, author: tuple[str, str] | None = None
    ) -> CommandResult:
        """Commit the staged tree."""
        args = ["commit", "-m", message]
        if author is not None:
            args += ["--author", f"{author[0]} <{author[1]}>"]
        return self._commands.run(_git(path, args))

    def push(self, path: str, remote: str = "origin", branch: str | None = None) -> CommandResult:
        """Push to a remote."""
        args = ["push", remote]
        if branch is not None:
            args.append(branch)
        return self._commands.run(_git(path, args))

    def pull(self, path: str, remote: str = "origin", branch: str | None = None) -> CommandResult:
        """Pull from a remote."""
        args = ["pull", remote]
        if branch is not None:
            args.append(branch)
        return self._commands.run(_git(path, args))

    def set_config(self, path: str, key: str, value: str, *, scope: str = "local") -> CommandResult:
        """Set a config value in the given scope (default ``local``)."""
        flag = "--global" if scope == "global" else "--local"
        return self._commands.run(_git(path, ["config", flag, key, value]))

    def get_config(self, path: str, key: str) -> CommandResult:
        """Read a config value."""
        return self._commands.run(_git(path, ["config", "--get", key]))

    def configure_user(self, path: str, name: str, email: str) -> CommandResult:
        """Set ``user.name`` and ``user.email`` for the repository."""
        self.set_config(path, "user.name", name)
        return self.set_config(path, "user.email", email)

    def dangerously_authenticate(self, *args: object, **kwargs: object) -> None:
        """Unsupported: ``e2b`` stores the credential in its cloud
        credential helper, which has no local counterpart.

        Configure a credential helper or an SSH key inside the sandbox
        instead — ``git`` there is an ordinary program."""
        del args, kwargs
        unsupported(
            "git.dangerously_authenticate",
            "there is no cloud credential store; configure git credentials inside the sandbox",
        )
