# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arcbox/sandbox/v1/errors.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'arcbox/sandbox/v1/errors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61rcbox/sandbox/v1/errors.proto\x12\x11\x61rcbox.sandbox.v1\"\xb7\x01\n\tErrorInfo\x12*\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1c.arcbox.sandbox.v1.ErrorCode\x12\x12\n\nsuggestion\x18\x02 \x01(\t\x12:\n\x07\x63ontext\x18\x03 \x03(\x0b\x32).arcbox.sandbox.v1.ErrorInfo.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xf1\x04\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12 \n\x1c\x45RROR_CODE_SANDBOX_NOT_FOUND\x10\x01\x12!\n\x1d\x45RROR_CODE_TEMPLATE_NOT_FOUND\x10\x02\x12\"\n\x1e\x45RROR_CODE_EXECUTION_NOT_FOUND\x10\x03\x12\x1d\n\x19\x45RROR_CODE_FILE_NOT_FOUND\x10\x04\x12\x1d\n\x19\x45RROR_CODE_SANDBOX_PAUSED\x10\x05\x12 \n\x1c\x45RROR_CODE_SANDBOX_NOT_READY\x10\x06\x12\x1d\n\x19\x45RROR_CODE_SANDBOX_FAILED\x10\x07\x12\x1a\n\x16\x45RROR_CODE_TTL_EXPIRED\x10\x08\x12\x1e\n\x1a\x45RROR_CODE_COMMAND_TIMEOUT\x10\t\x12&\n\"ERROR_CODE_NESTED_VIRT_UNSUPPORTED\x10\n\x12\x1f\n\x1b\x45RROR_CODE_TEMPLATE_INVALID\x10\x0b\x12\x1d\n\x19\x45RROR_CODE_FILE_TOO_LARGE\x10\x0c\x12\x1b\n\x17\x45RROR_CODE_STDIN_CLOSED\x10\r\x12\x1b\n\x17\x45RROR_CODE_TTY_REQUIRED\x10\x0e\x12\x1a\n\x16\x45RROR_CODE_PORT_IN_USE\x10\x0f\x12\x1c\n\x18\x45RROR_CODE_AUTH_REQUIRED\x10\x10\x12 \n\x1c\x45RROR_CODE_PROTOCOL_MISMATCH\x10\x11\x12&\n\"ERROR_CODE_RESOURCE_EXHAUSTED_HOST\x10\x12\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arcbox.sandbox.v1.errors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORINFO_CONTEXTENTRY']._loaded_options = None
  _globals['_ERRORINFO_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_ERRORCODE']._serialized_start=240
  _globals['_ERRORCODE']._serialized_end=865
  _globals['_ERRORINFO']._serialized_start=54
  _globals['_ERRORINFO']._serialized_end=237
  _globals['_ERRORINFO_CONTEXTENTRY']._serialized_start=191
  _globals['_ERRORINFO_CONTEXTENTRY']._serialized_end=237
# @@protoc_insertion_point(module_scope)
